# Generated by Django 3.0.8 on 2020-09-28 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_21sep20'),
    ]

    operations = [
        migrations.AddField(
            model_name='kejadian',
            name='divisi',
            field=models.CharField(choices=[('G', 'GENERAL'), ('R', 'ROASTERY'), ('Q', 'QC'), ('P', 'PRODUKSI'), ('S', 'SYSTEM')], default='G', max_length=1),
        ),
    ]
