# Generated by Django 3.0.8 on 2020-09-28 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_28sep20'),
        ('production', '0012_auto_28sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondiv',
            name='roasted_material',
            field=models.ManyToManyField(limit_choices_to={'next_process': False}, to='products.Roaster'),
        ),
    ]
