# Generated by Django 3.0.8 on 2020-09-21 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_17sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 9, 21)),
        ),
    ]
