# Generated by Django 3.0.8 on 2020-09-28 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_21sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='beans_name',
            field=models.ForeignKey(limit_choices_to={'show_this': True}, on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang'),
        ),
    ]
