# Generated by Django 3.0.8 on 2020-12-01 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_28sep20'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(default='X', max_length=7)),
                ('client_name', models.CharField(default='-', max_length=30)),
                ('pic', models.CharField(default='-', max_length=30)),
                ('no_telp', models.CharField(default='0', max_length=30)),
                ('alamat', models.CharField(default='-', max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
        migrations.CreateModel(
            name='ForeignMaterialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date(2020, 12, 1))),
                ('shift', models.CharField(choices=[('P', 'PAGI'), ('S', 'SIANG'), ('M', 'MALAM')], default='-', max_length=1)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.RoasterName')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignMaterialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jenis_FM', models.CharField(default='-', max_length=50)),
                ('catatan', models.TextField(default='-', max_length=300)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ForeignMaterialReport')),
                ('nama_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.BeansGudang')),
            ],
        ),
        migrations.AddField(
            model_name='beanscode',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.ClientName'),
        ),
    ]
