# Generated by Django 3.0.8 on 2020-12-02 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_1dec20'),
    ]

    operations = [
        migrations.AddField(
            model_name='beanscode',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.ClientName'),
        ),
        migrations.AlterField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 12, 2)),
        ),
        migrations.AlterField(
            model_name='foreignmaterialreport',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 12, 2)),
        ),
    ]
